packages:
  - "apps/*"
  - "packages/templates"
  - "packages/abacus-react"
  - "packages/llm-client"
  - "packages/core/client/node"
  - "packages/core/client/typescript"
  - "packages/core/client/browser"
