name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/src/**'
      - 'apps/web/.storybook/**'
      - 'packages/abacus-react/**'
      - '.gitea/workflows/deploy-storybook.yml'
  workflow_dispatch:

jobs:
  # Fast build on MacBook (when available)
  build-fast:
    name: Build (MacBook)
    runs-on: macbook
    timeout-minutes: 10
    continue-on-error: true
    outputs:
      success: ${{ steps.mark-success.outputs.success }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate build info
        working-directory: apps/web
        run: node scripts/generate-build-info.js

      - name: Generate Panda CSS
        working-directory: apps/web
        run: |
          pnpm panda codegen
          npx @pandacss/dev cssgen || echo "CSS generation had warnings but continued"

      - name: Build workspace packages
        run: pnpm turbo build --filter=@soroban/llm-client --filter=@soroban/abacus-react

      - name: Build web Storybook
        working-directory: apps/web
        run: pnpm build-storybook --output-dir ../../storybook-static/web

      - name: Build abacus-react Storybook
        working-directory: packages/abacus-react
        run: pnpm build-storybook --output-dir ../../storybook-static/abacus-react

      - name: Create index page
        run: |
          cat > storybook-static/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Soroban Abacus Flashcards - Storybooks</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 800px;
                      margin: 40px auto;
                      padding: 20px;
                      line-height: 1.6;
                      color: #333;
                      background: #f5f5f5;
                  }
                  .header { text-align: center; margin-bottom: 40px; }
                  h1 { color: #ff4785; }
                  .storybook-links { display: grid; gap: 20px; margin-top: 30px; }
                  .storybook-card {
                      border: 1px solid #e1e5e9;
                      border-radius: 8px;
                      padding: 24px;
                      text-decoration: none;
                      color: inherit;
                      background: white;
                      transition: all 0.2s ease;
                  }
                  .storybook-card:hover {
                      border-color: #ff4785;
                      box-shadow: 0 4px 12px rgba(255, 71, 133, 0.15);
                      transform: translateY(-2px);
                  }
                  .storybook-title { font-size: 1.25rem; font-weight: 600; margin-bottom: 8px; color: #ff4785; }
                  .storybook-description { color: #666; margin: 0; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>Soroban Abacus Flashcards</h1>
                  <p>Interactive component documentation</p>
              </div>
              <div class="storybook-links">
                  <a href="./web/" class="storybook-card">
                      <div class="storybook-title">Web Application Storybook</div>
                      <p class="storybook-description">Complete web app components: games, tutorials, and UI elements</p>
                  </a>
                  <a href="./abacus-react/" class="storybook-card">
                      <div class="storybook-title">Abacus React Component</div>
                      <p class="storybook-description">Interactive React abacus with animations and place value editing</p>
                  </a>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy to NAS
        env:
          NAS_SSH_KEY: ${{ secrets.NAS_SSH_KEY }}
          NAS_HOST: ${{ secrets.NAS_HOST }}
          NAS_DEPLOY_PATH: ${{ secrets.NAS_DEPLOY_PATH }}
        run: |
          set -ex

          if [ -z "$NAS_HOST" ] || [ -z "$NAS_DEPLOY_PATH" ] || [ -z "$NAS_SSH_KEY" ]; then
            echo "ERROR: Missing required secrets"
            exit 1
          fi

          mkdir -p ~/.ssh
          echo "$NAS_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$NAS_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true

          rsync -avz --delete \
            storybook-static/ \
            "antialias@${NAS_HOST}:${NAS_DEPLOY_PATH}/"

          echo "Storybook deployed to https://dev.abaci.one/storybook/"

      - name: Mark success
        id: mark-success
        run: echo "success=true" >> $GITHUB_OUTPUT

  # Fallback build on k3s (when MacBook unavailable)
  build-fallback:
    name: Build (k3s fallback)
    runs-on: ubuntu-latest
    needs: build-fast
    if: ${{ always() && needs.build-fast.outputs.success != 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure caching
        run: |
          mkdir -p /cache/pnpm-store /cache/turbo
          pnpm config set store-dir /cache/pnpm-store

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate build info
        working-directory: apps/web
        run: node scripts/generate-build-info.js

      - name: Generate Panda CSS
        working-directory: apps/web
        run: |
          pnpm panda codegen
          npx @pandacss/dev cssgen || echo "CSS generation had warnings but continued"

      - name: Build workspace packages
        env:
          TURBO_CACHE_DIR: /cache/turbo
        run: pnpm turbo build --filter=@soroban/llm-client --filter=@soroban/abacus-react --cache-dir=/cache/turbo

      - name: Build web Storybook
        working-directory: apps/web
        run: pnpm build-storybook --output-dir ../../storybook-static/web

      - name: Build abacus-react Storybook
        working-directory: packages/abacus-react
        run: pnpm build-storybook --output-dir ../../storybook-static/abacus-react

      - name: Create index page
        run: |
          cat > storybook-static/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Soroban Abacus Flashcards - Storybooks</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 800px;
                      margin: 40px auto;
                      padding: 20px;
                      line-height: 1.6;
                      color: #333;
                      background: #f5f5f5;
                  }
                  .header { text-align: center; margin-bottom: 40px; }
                  h1 { color: #ff4785; }
                  .storybook-links { display: grid; gap: 20px; margin-top: 30px; }
                  .storybook-card {
                      border: 1px solid #e1e5e9;
                      border-radius: 8px;
                      padding: 24px;
                      text-decoration: none;
                      color: inherit;
                      background: white;
                      transition: all 0.2s ease;
                  }
                  .storybook-card:hover {
                      border-color: #ff4785;
                      box-shadow: 0 4px 12px rgba(255, 71, 133, 0.15);
                      transform: translateY(-2px);
                  }
                  .storybook-title { font-size: 1.25rem; font-weight: 600; margin-bottom: 8px; color: #ff4785; }
                  .storybook-description { color: #666; margin: 0; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>Soroban Abacus Flashcards</h1>
                  <p>Interactive component documentation</p>
              </div>
              <div class="storybook-links">
                  <a href="./web/" class="storybook-card">
                      <div class="storybook-title">Web Application Storybook</div>
                      <p class="storybook-description">Complete web app components: games, tutorials, and UI elements</p>
                  </a>
                  <a href="./abacus-react/" class="storybook-card">
                      <div class="storybook-title">Abacus React Component</div>
                      <p class="storybook-description">Interactive React abacus with animations and place value editing</p>
                  </a>
              </div>
          </body>
          </html>
          EOF

      - name: Install deployment tools
        run: apt-get update && apt-get install -y rsync openssh-client

      - name: Deploy to NAS
        env:
          NAS_SSH_KEY: ${{ secrets.NAS_SSH_KEY }}
          NAS_HOST: ${{ secrets.NAS_HOST }}
          NAS_DEPLOY_PATH: ${{ secrets.NAS_DEPLOY_PATH }}
        run: |
          set -ex

          if [ -z "$NAS_HOST" ] || [ -z "$NAS_DEPLOY_PATH" ] || [ -z "$NAS_SSH_KEY" ]; then
            echo "ERROR: Missing required secrets"
            exit 1
          fi

          mkdir -p ~/.ssh
          echo "$NAS_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$NAS_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true

          rsync -avz --delete \
            storybook-static/ \
            "antialias@${NAS_HOST}:${NAS_DEPLOY_PATH}/"

          echo "Storybook deployed to https://dev.abaci.one/storybook/"

# v16 - MacBook runner with k3s fallback
