# Configuration for 3-column fixed width display
range: "0-999"
cards_per_page: 6
paper_size: "us-letter"
orientation: "portrait"
margins:
  top: "0.5in"
  bottom: "0.5in"
  left: "0.5in"
  right: "0.5in"
gutter: "5mm"
show_cut_marks: true
show_registration: false
font_family: "DejaVu Sans"
font_size: "36pt"
columns: 3
show_empty_columns: true
shuffle: false
