# Configuration for traditional circle-shaped beads
range: "0-9"
cards_per_page: 6
paper_size: "us-letter"
orientation: "portrait"
margins:
  top: "0.5in"
  bottom: "0.5in"
  left: "0.5in"
  right: "0.5in"
gutter: "5mm"
show_cut_marks: false
show_registration: false
font_family: "DejaVu Sans"
font_size: "48pt"
columns: auto
show_empty_columns: false
hide_inactive_beads: false
bead_shape: "circle" # Use traditional circular beads
shuffle: false
