# Configuration with colored numerals to match bead colors
# This makes it easy for learners to connect the visual representation
# with the numerical value, especially for place value understanding
range: "0-999"
cards_per_page: 6
paper_size: "us-letter"
orientation: "portrait"
margins:
  top: "0.5in"
  bottom: "0.5in"
  left: "0.5in"
  right: "0.5in"
gutter: "5mm"
show_cut_marks: true
show_registration: false
font_family: "DejaVu Sans"
font_size: "48pt"
columns: 3
show_empty_columns: true
hide_inactive_beads: false
bead_shape: "diamond"
color_scheme: "place-value"
colored_numerals: true # Color the numerals to match the bead colors
shuffle: false
