# Configuration for counting by 5s
# Useful for practicing skip counting and multiplication tables
range: "0-100"
step: 5  # Count by 5s: 0, 5, 10, 15, 20, ...
cards_per_page: 6
paper_size: "us-letter"
orientation: "portrait"
margins:
  top: "0.5in"
  bottom: "0.5in"
  left: "0.5in"
  right: "0.5in"
gutter: "5mm"
show_cut_marks: true
show_registration: false
font_family: "DejaVu Sans"
font_size: "48pt"
columns: auto
show_empty_columns: false
hide_inactive_beads: false
bead_shape: "diamond"
shuffle: false